// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/storage/storage.proto

package storage_storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceAction int32

const (
	// In proto3, the first enum value must be 0 and acts as the default.
	DeviceAction_DEVICE_ACTION_UNSPECIFIED DeviceAction = 0
	DeviceAction_DEVICE_ACTION_ADD         DeviceAction = 1
	DeviceAction_DEVICE_ACTION_REMOVE      DeviceAction = 2
)

// Enum value maps for DeviceAction.
var (
	DeviceAction_name = map[int32]string{
		0: "DEVICE_ACTION_UNSPECIFIED",
		1: "DEVICE_ACTION_ADD",
		2: "DEVICE_ACTION_REMOVE",
	}
	DeviceAction_value = map[string]int32{
		"DEVICE_ACTION_UNSPECIFIED": 0,
		"DEVICE_ACTION_ADD":         1,
		"DEVICE_ACTION_REMOVE":      2,
	}
)

func (x DeviceAction) Enum() *DeviceAction {
	p := new(DeviceAction)
	*p = x
	return p
}

func (x DeviceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_storage_storage_proto_enumTypes[0].Descriptor()
}

func (DeviceAction) Type() protoreflect.EnumType {
	return &file_pkg_storage_storage_proto_enumTypes[0]
}

func (x DeviceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceAction.Descriptor instead.
func (DeviceAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{0}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevName       string                 `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	Bus           string                 `protobuf:"bytes,2,opt,name=bus,proto3" json:"bus,omitempty"`
	FsUuid        string                 `protobuf:"bytes,3,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	FsLabel       string                 `protobuf:"bytes,4,opt,name=fs_label,json=fsLabel,proto3" json:"fs_label,omitempty"`
	FsSize        int64                  `protobuf:"varint,5,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	FsType        string                 `protobuf:"bytes,6,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	FsVersion     string                 `protobuf:"bytes,7,opt,name=fs_version,json=fsVersion,proto3" json:"fs_version,omitempty"`
	Model         string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	MountName     string                 `protobuf:"bytes,9,opt,name=mount_name,json=mountName,proto3" json:"mount_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_pkg_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *Device) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *Device) GetFsUuid() string {
	if x != nil {
		return x.FsUuid
	}
	return ""
}

func (x *Device) GetFsLabel() string {
	if x != nil {
		return x.FsLabel
	}
	return ""
}

func (x *Device) GetFsSize() int64 {
	if x != nil {
		return x.FsSize
	}
	return 0
}

func (x *Device) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *Device) GetFsVersion() string {
	if x != nil {
		return x.FsVersion
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetMountName() string {
	if x != nil {
		return x.MountName
	}
	return ""
}

type DeviceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        DeviceAction           `protobuf:"varint,1,opt,name=action,proto3,enum=storage.v1.DeviceAction" json:"action,omitempty"`
	Device        *Device                `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEvent) Reset() {
	*x = DeviceEvent{}
	mi := &file_pkg_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEvent) ProtoMessage() {}

func (x *DeviceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEvent.ProtoReflect.Descriptor instead.
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceEvent) GetAction() DeviceAction {
	if x != nil {
		return x.Action
	}
	return DeviceAction_DEVICE_ACTION_UNSPECIFIED
}

func (x *DeviceEvent) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type MountCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountCommand) Reset() {
	*x = MountCommand{}
	mi := &file_pkg_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountCommand) ProtoMessage() {}

func (x *MountCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountCommand.ProtoReflect.Descriptor instead.
func (*MountCommand) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *MountCommand) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_pkg_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{3}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_pkg_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_storage_storage_proto_rawDescGZIP(), []int{4}
}

var File_pkg_storage_storage_proto protoreflect.FileDescriptor

const file_pkg_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/storage/storage.proto\x12\n" +
	"storage.v1\"\xef\x01\n" +
	"\x06Device\x12\x19\n" +
	"\bdev_name\x18\x01 \x01(\tR\adevName\x12\x10\n" +
	"\x03bus\x18\x02 \x01(\tR\x03bus\x12\x17\n" +
	"\afs_uuid\x18\x03 \x01(\tR\x06fsUuid\x12\x19\n" +
	"\bfs_label\x18\x04 \x01(\tR\afsLabel\x12\x17\n" +
	"\afs_size\x18\x05 \x01(\x03R\x06fsSize\x12\x17\n" +
	"\afs_type\x18\x06 \x01(\tR\x06fsType\x12\x1d\n" +
	"\n" +
	"fs_version\x18\a \x01(\tR\tfsVersion\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"mount_name\x18\t \x01(\tR\tmountName\"k\n" +
	"\vDeviceEvent\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.storage.v1.DeviceActionR\x06action\x12*\n" +
	"\x06device\x18\x02 \x01(\v2\x12.storage.v1.DeviceR\x06device\":\n" +
	"\fMountCommand\x12*\n" +
	"\x06device\x18\x01 \x01(\v2\x12.storage.v1.DeviceR\x06device\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse*^\n" +
	"\fDeviceAction\x12\x1d\n" +
	"\x19DEVICE_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEVICE_ACTION_ADD\x10\x01\x12\x18\n" +
	"\x14DEVICE_ACTION_REMOVE\x10\x022\xa3\x01\n" +
	"\rStorageBridge\x12E\n" +
	"\x0fReportUdevEvent\x12\x17.storage.v1.DeviceEvent\x1a\x19.storage.v1.EmptyResponse\x12K\n" +
	"\x13StreamMountCommands\x12\x18.storage.v1.EmptyRequest\x1a\x18.storage.v1.MountCommand0\x01BP\n" +
	"\x1eit.lysz210.akasha.dozob.api.v1P\x01Z,github.com/lysz210/dozob/pkg/storage:storageb\x06proto3"

var (
	file_pkg_storage_storage_proto_rawDescOnce sync.Once
	file_pkg_storage_storage_proto_rawDescData []byte
)

func file_pkg_storage_storage_proto_rawDescGZIP() []byte {
	file_pkg_storage_storage_proto_rawDescOnce.Do(func() {
		file_pkg_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_storage_storage_proto_rawDesc), len(file_pkg_storage_storage_proto_rawDesc)))
	})
	return file_pkg_storage_storage_proto_rawDescData
}

var file_pkg_storage_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_storage_storage_proto_goTypes = []any{
	(DeviceAction)(0),     // 0: storage.v1.DeviceAction
	(*Device)(nil),        // 1: storage.v1.Device
	(*DeviceEvent)(nil),   // 2: storage.v1.DeviceEvent
	(*MountCommand)(nil),  // 3: storage.v1.MountCommand
	(*EmptyRequest)(nil),  // 4: storage.v1.EmptyRequest
	(*EmptyResponse)(nil), // 5: storage.v1.EmptyResponse
}
var file_pkg_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.v1.DeviceEvent.action:type_name -> storage.v1.DeviceAction
	1, // 1: storage.v1.DeviceEvent.device:type_name -> storage.v1.Device
	1, // 2: storage.v1.MountCommand.device:type_name -> storage.v1.Device
	2, // 3: storage.v1.StorageBridge.ReportUdevEvent:input_type -> storage.v1.DeviceEvent
	4, // 4: storage.v1.StorageBridge.StreamMountCommands:input_type -> storage.v1.EmptyRequest
	5, // 5: storage.v1.StorageBridge.ReportUdevEvent:output_type -> storage.v1.EmptyResponse
	3, // 6: storage.v1.StorageBridge.StreamMountCommands:output_type -> storage.v1.MountCommand
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_storage_storage_proto_init() }
func file_pkg_storage_storage_proto_init() {
	if File_pkg_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_storage_storage_proto_rawDesc), len(file_pkg_storage_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_storage_storage_proto_goTypes,
		DependencyIndexes: file_pkg_storage_storage_proto_depIdxs,
		EnumInfos:         file_pkg_storage_storage_proto_enumTypes,
		MessageInfos:      file_pkg_storage_storage_proto_msgTypes,
	}.Build()
	File_pkg_storage_storage_proto = out.File
	file_pkg_storage_storage_proto_goTypes = nil
	file_pkg_storage_storage_proto_depIdxs = nil
}
