// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/storage/storage.proto

package storage_storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageBridge_ReportUdevEvent_FullMethodName     = "/storage.v1.StorageBridge/ReportUdevEvent"
	StorageBridge_StreamMountCommands_FullMethodName = "/storage.v1.StorageBridge/StreamMountCommands"
)

// StorageBridgeClient is the client API for StorageBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageBridgeClient interface {
	ReportUdevEvent(ctx context.Context, in *DeviceEvent, opts ...grpc.CallOption) (*EmptyResponse, error)
	StreamMountCommands(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MountCommand], error)
}

type storageBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageBridgeClient(cc grpc.ClientConnInterface) StorageBridgeClient {
	return &storageBridgeClient{cc}
}

func (c *storageBridgeClient) ReportUdevEvent(ctx context.Context, in *DeviceEvent, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, StorageBridge_ReportUdevEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageBridgeClient) StreamMountCommands(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MountCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageBridge_ServiceDesc.Streams[0], StorageBridge_StreamMountCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmptyRequest, MountCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageBridge_StreamMountCommandsClient = grpc.ServerStreamingClient[MountCommand]

// StorageBridgeServer is the server API for StorageBridge service.
// All implementations must embed UnimplementedStorageBridgeServer
// for forward compatibility.
type StorageBridgeServer interface {
	ReportUdevEvent(context.Context, *DeviceEvent) (*EmptyResponse, error)
	StreamMountCommands(*EmptyRequest, grpc.ServerStreamingServer[MountCommand]) error
	mustEmbedUnimplementedStorageBridgeServer()
}

// UnimplementedStorageBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageBridgeServer struct{}

func (UnimplementedStorageBridgeServer) ReportUdevEvent(context.Context, *DeviceEvent) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUdevEvent not implemented")
}
func (UnimplementedStorageBridgeServer) StreamMountCommands(*EmptyRequest, grpc.ServerStreamingServer[MountCommand]) error {
	return status.Error(codes.Unimplemented, "method StreamMountCommands not implemented")
}
func (UnimplementedStorageBridgeServer) mustEmbedUnimplementedStorageBridgeServer() {}
func (UnimplementedStorageBridgeServer) testEmbeddedByValue()                       {}

// UnsafeStorageBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageBridgeServer will
// result in compilation errors.
type UnsafeStorageBridgeServer interface {
	mustEmbedUnimplementedStorageBridgeServer()
}

func RegisterStorageBridgeServer(s grpc.ServiceRegistrar, srv StorageBridgeServer) {
	// If the following call panics, it indicates UnimplementedStorageBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageBridge_ServiceDesc, srv)
}

func _StorageBridge_ReportUdevEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageBridgeServer).ReportUdevEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageBridge_ReportUdevEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageBridgeServer).ReportUdevEvent(ctx, req.(*DeviceEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageBridge_StreamMountCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageBridgeServer).StreamMountCommands(m, &grpc.GenericServerStream[EmptyRequest, MountCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageBridge_StreamMountCommandsServer = grpc.ServerStreamingServer[MountCommand]

// StorageBridge_ServiceDesc is the grpc.ServiceDesc for StorageBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.StorageBridge",
	HandlerType: (*StorageBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportUdevEvent",
			Handler:    _StorageBridge_ReportUdevEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMountCommands",
			Handler:       _StorageBridge_StreamMountCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/storage/storage.proto",
}
